---

- name: Retrieve the SSH public key on the rsnapshot master
  delegate_to: "{{ rsnapshot_master_host }}"
  remote_user: "{{ rsnapshot_master_host_user }}"
  command: "cat $HOME/.ssh/{{ rsnapshot_master_ssh_key }}.pub"
  register: rsnapshot_master_ssh_pubkey
  changed_when: False
  always_run: True

- name: Set the SSH public key for the backup system user
  authorized_key:
    user: "{{ rsnapshot_slave_user }}"
    key: "{{ rsnapshot_master_ssh_pubkey.stdout }}"
  when: rsnapshot_master_ssh_pubkey
